src/DataEntryPanel.cpp
src/MapRenderer3D.cpp
src/MapRenderer3D.h

Normal translucency (left), Additive translucency (right)

Some fixes/updates

---

Info.plist
src/ArchiveManager.cpp
src/MIDIPlayer.cpp
src/Main.h
src/MainApp.cpp
src/MainApp.h
src/MainWindow.cpp
src/SAuiTabArt.cpp
src/SLADEMap.cpp
src/SToolBar.cpp
src/TextEditor.cpp
src/lzma/C/Threads.h

These are all remaining changes from my OS X fork.

Changes from OS X fork

---

dist/CMakeLists.txt
src/CMakeLists.txt

Now it's generator-agnostic
Building and debugging in Xcode is working

Rework OS X application bundle creation via CMake

---

src/MapLine.cpp
src/MapRenderer3D.cpp
src/MapSector.cpp
src/MapSector.h
src/MapSpecials.cpp
src/SLADEMap.cpp

Finally gave the 3.1.1 branch a go.  Fixed some places that were assuming flat flats, salvaged what I could from my other branch.  :)
I think I have an idea for making live updating of slopes work without being too invasive — it involves calculating the planes on the fly (like I did before), caching the results, and flushing the cache when any part of the sector or anything inside it changes.  All the slope mechanisms only work on the sector they're in or part of, thankfully.

Some slope support improvements

---

src/AudioEntryPanel.cpp
src/CMakeLists.txt
src/Dialogs/Preferences/AudioPrefsPanel.cpp
src/Dialogs/Preferences/AudioPrefsPanel.h
src/MIDIPlayer.cpp
src/MIDIPlayer.h

Some fixes & updates

---

src/Dialogs/Preferences/MapEditorPrefsPanel.cpp
src/Dialogs/Preferences/MapEditorPrefsPanel.h
src/MapCanvas.cpp

Seems useful, and the notion of a double click doesn't make much sense to the keybind system.

Double-click to edit the current selection

---

src/DirArchive.cpp

Fixed sirjuddington-code in DirArchive

---

src/BrowserCanvas.cpp
src/BrowserCanvas.h
src/BrowserWindow.cpp
src/Dialogs/RunDialog.cpp
src/InfoOverlay3d.cpp
src/MapCanvas.cpp
src/MapEditor.cpp
src/MapRenderer3D.cpp
src/Structs.h
src/ThingTypeBrowser.cpp

Some little things that I never got around to individually.  Some UI, a couple editing bugs.  Commits should be pretty independent, so feel free to cherry pick if you have any objections  :)

Fix some papercuts

---

src/ActionSpecialDialog.cpp
src/ActionSpecialDialog.h
src/MapEditor.cpp

Now you don't need to re-select the item, just click  twice and slade will automatically jump to the args tab.

Some ActionSpecialDialog improvements

---

src/Archive.h
src/ArchiveFormats.h
src/ArchiveManager.cpp
src/Archives.h
src/ChasmBinArchive.cpp
src/ChasmBinArchive.h

See descriptions of commits for more details.

Support for Chasm: The Rift bin archives 

---

dist/res/config/games/include/things_doom1.cfg
dist/res/config/ports/include/props_zdoom.cfg
dist/res/config/ports/include/specials_zdoom.cfg
src/ActionSpecialDialog.cpp
src/ActionSpecialDialog.h
src/DirArchive.cpp
src/MapChecks.cpp
src/MapObjectPropsPanel.cpp
src/MapRenderer3D.cpp
src/SLADEMap.cpp
src/SLADEMap.h
src/SToolBarButton.cpp
src/TextLanguage.cpp

I did a lot of mapping recently and took notes on things that were broken or annoying and here you go.

Misc 3.1.1 fixes

---

src/ActionSpecialDialog.cpp

https://github.com/sirjuddington/SLADE/pull/325

Small bugfix

---

src/Dialogs/Preferences/AudioPrefsPanel.cpp
src/EntryDataFormat.cpp
src/MIDIPlayer.cpp

Fixed these errors when I tried to compile slade.
L2Test your code!

Code quality control alarm

---

src/ArchivePanel.cpp

Cancelation of save file dialog is no longer exhibit undefined behavior

Fixed potential crash with 'Build Archive' feature

---

src/ArchiveEntryList.cpp
src/ArchiveEntryList.h
src/ArchivePanel.cpp
src/WadArchive.cpp

This is just my attempt to fix this old issue. (I hate it)
Works with all entry operations.
I hope, nothing is broken.
Before:
https://www.youtube.com/watch?v=Mg-7z-DhmxA&feature=youtu.be
After:
https://www.youtube.com/watch?v=qUzJVo9Ud7o&feature=youtu.be

Optimized EntryPanel code

---

src/MapEditor.cpp
src/MapLine.cpp
src/MathStuff.cpp

I made a couple booboos, which expressed themselves in the form of some extremely bizarre merges with particular geometry in particular positions.

Point branch followup

---

src/Dialogs/RunDialog.cpp

Added ability to run game executable using OS X application bundle
Fixed check for empty path of game executable to run

Run game executable fixes

---

CONTRIBUTING.md
dist/res/config/ports/include/specials_zdoom.cfg
src/ActionSpecialDialog.cpp
src/Main.h
src/MapCanvas.cpp
src/MapEditor.cpp
src/MapLine.h
src/MapSector.h
src/MapThing.h
src/MapVertex.h
src/SLADEMap.cpp
src/SectorBuilder.cpp

Pretty tame; stuff I ran into while blogging about Doom mapping last month.

Yet more papercuts

---

dist/res/config/games/include/specials_doom1.cfg
dist/res/config/games/include/specials_doom2.cfg
dist/res/config/games/include/specials_heretic.cfg
dist/res/config/games/include/specials_strife.cfg
src/ArchivePanel.cpp
src/ArchivePanel.h
src/BrowserCanvas.cpp
src/EntryOperations.cpp
src/EntryOperations.h
src/MainApp.cpp
src/STabCtrl.cpp
src/TextureXList.cpp
src/TextureXList.h

Fixed a few signed/unsigned mismatch warnings
Fixed missing music to MIDI conversion
Added a texture error report function

Various fixes

---

dist/res/config/ports/include/specials_zdoom.cfg
src/ActionSpecialDialog.cpp
src/ArchiveOperations.cpp
src/Args.h
src/ColourConfiguration.cpp
src/Console.cpp
src/DefaultEntryPanel.cpp
src/DirArchive.cpp
src/DirArchive.h
src/GfxConvDialog.cpp
src/LineTextureOverlay.cpp
src/PaletteEntryPanel.cpp
src/PatchTablePanel.cpp
src/Polygon2D.cpp
src/SectorTextureOverlay.cpp
src/TextLanguage.cpp

I'm running low on papercuts!  Nice.
Second commit fixes #446, too.  (There's a looming question of what should happen if you delete entry A, then recreate it.)

Even more papercuts

---

src/Dialogs/ModifyOffsetsDialog.cpp
src/MainEditor/UI/EntryPanel/AudioEntryPanel.cpp
src/MainEditor/UI/EntryPanel/DefaultEntryPanel.cpp
src/MainEditor/UI/EntryPanel/GfxEntryPanel.cpp
src/MapEditor/UI/Dialogs/ActionSpecialDialog.cpp
src/MapEditor/UI/PropsPanel/MapObjectPropsPanel.cpp

Fixes a couple things reported on the ZDoom forums, plus a quirk someone mentioned on the last PR.

Papercuts 5: the reckoning

---

src/MainEditor/UI/EntryPanel/AudioEntryPanel.cpp
src/MainEditor/UI/EntryPanel/DefaultEntryPanel.cpp

Re discussion at: https://github.com/sirjuddington/SLADE/commit/083007d7a7c0c92eac008940564f521467f368b5#commitcomment-16426584

Remove %zu for now to fix a crash

---

src/MainEditor/MainWindow.cpp

Fixed opening of recent items from non-WebView start page

Fix for non-WebView recent items

---

src/MapEditor/UI/MapCanvas.cpp

Disabled sound alerts in map editor on OS X

---

src/Archive/Formats/DirArchive.cpp
src/MapEditor/MapEditor.cpp
src/MapEditor/Renderer/MapRenderer2D.cpp
src/MapEditor/Renderer/MapRenderer3D.cpp
src/MapEditor/Renderer/Overlays/InfoOverlay3d.cpp
src/MapEditor/SLADEMap/MapLine.cpp
src/MapEditor/SLADEMap/MapObject.cpp
src/MapEditor/SLADEMap/MapSector.cpp
src/MapEditor/SLADEMap/SLADEMap.cpp
src/MapEditor/SectorBuilder.cpp

Fixed some things I stumbled upon while mapping for DUMP 2.
The only not-quite-trivial change is the "enclosed void" one.  I hammered on it for a bit and couldn't come up with any pathological cases that broke catastrophically.

Papercuts 6

---

src/MainEditor/UI/ArchivePanel.cpp

- Added progress bar & more info
- Added new CVAR archive_build_skip_hidden to skip hidden files
(example: .git) It's very useful if you use git/hg in your projects
- Added: cancel building on Escape

Improve Build Archive feature

---

src/Archive/ArchiveManager.cpp
src/Archive/ArchiveManager.h
src/MainEditor/UI/ArchivePanel.cpp

This finally removed "archive lag".
and this also increased archive building speed, because I removed useless announcers.

Added optimization for archive building

---

src/MapEditor/Renderer/Overlays/ThingInfoOverlay.cpp

See https://github.com/sirjuddington/SLADE/pull/526

Normalize overlay actor texture size

---

src/Dialogs/Preferences/ACSPrefsPanel.cpp
src/MainEditor/EntryOperations.cpp
src/MainEditor/UI/ArchiveManagerPanel.cpp
src/MainEditor/UI/ArchiveManagerPanel.h
src/MainEditor/UI/ArchivePanel.cpp
src/MainEditor/UI/ArchivePanel.h

Prevent tab manager from opening entry in archive tab and in its own tab in the same time:
http://rgho.st/8rnKZlbL4

Some cool changes

---

src/General/ResourceManager.cpp

These changes were backported from my other fix/full_path_textures branch.
I've also set up this pull request to be merged into the stable branch rather than master.

Make SLADE recognize full path texture names.

---

dist/res/config/languages/decorate.txt

ZDoom language configurations update

---

src/UI/Lists/ArchiveEntryList.cpp

solves issue #523 and issue #531

Convert wxString to wxChar before using compareTo()

---

dist/res/config/ports/eternity.cfg
dist/res/config/ports/include/flags_eternity.cfg
dist/res/config/ports/include/props_eternity.cfg
dist/res/config/ports/include/sectors_eternity.cfg
dist/res/config/ports/include/specials_eternity.cfg
src/MapEditor/MapChecks.cpp
src/MapEditor/MapEditor.cpp
src/MapEditor/MapSpecials.cpp
src/MapEditor/MapSpecials.h
src/MapEditor/Renderer/MapRenderer2D.cpp
src/MapEditor/Renderer/MapRenderer3D.cpp
src/MapEditor/Renderer/Overlays/InfoOverlay3d.cpp
src/MapEditor/SLADEMap/MapSector.cpp

Also has various updates. Sorry about some of the commit messages being a bit odd.

Eternity UDMF Support

---

dist/res/config/ports/include/specials_eternity.cfg
src/MapEditor/MapSpecials.cpp

This has been tested. It's a small and simple change.

Add Plane_Copy to EE config; update comment

---

dist/res/config/entry_types/types_text.txt

Reverts sirjuddington/SLADE#599 I will make a better pull request soon.

Revert "Allow editing of SOC lumps in the text editor."

---

src/Application/MainApp.cpp
src/Archive/Archive.cpp
src/Archive/ArchiveEntry.cpp
src/Archive/ArchiveEntry.h
src/Archive/EntryType/EntryType.cpp
src/Archive/Formats/WadArchive.cpp
src/General/Clipboard.cpp
src/General/Misc.cpp
src/General/ResourceManager.cpp
src/Graphics/Icons.cpp
src/MainEditor/UI/ArchiveManagerPanel.cpp
src/MainEditor/UI/ArchiveManagerPanel.h
src/MainEditor/UI/ArchivePanel.cpp
src/UI/Lists/VirtualListView.cpp
src/UI/TextEditor/Lexer.cpp
src/UI/TextEditor/TextLanguage.cpp
src/Utility/Tokenizer.cpp
src/Utility/Tokenizer.h

disable archive list width update while pasting

a bunch of optimization stuff

---

src/Archive/Archive.cpp
src/Archive/Archive.h
src/Archive/ArchiveEntry.h
src/General/ResourceManager.cpp
src/General/ResourceManager.h
src/Graphics/CTexture/CTexture.h
src/MainEditor/UI/TextureXEditor/PatchBrowser.cpp
src/MapEditor/MapTextureManager.cpp

Now if an entry is deleted but not removed from the resource manager for whatever reason, it can tell via weak_ptr.
Bit of a band-aid fix at the moment but I want to move over to using smart pointers for this kind of thing anyway, might as well start here.

Use smart pointers in Archive and ResourceManager

---

src/Archive/Formats/WadArchive.cpp
src/MainEditor/MainWindow.cpp
src/MainEditor/UI/ArchiveManagerPanel.cpp
src/MapEditor/MapEditorWindow.cpp
src/MapEditor/MapEditorWindow.h

The first two cause crashes using wxWidgets 3.0.2 (debian stretch).

Fix some UI-related bugs

---

src/Application/MainApp.cpp
src/MapEditor/SLADEMap/MapSector.cpp

Correctly restore sector heights after undo

---

src/Dialogs/TranslationEditorDialog.cpp
src/Dialogs/TranslationEditorDialog.h
src/Graphics/SImage/SImage.cpp
src/Graphics/SImage/SImage.h
src/UI/ColourBox.cpp
src/UI/ColourBox.h

Left click brings up a standard color selection dialog; but right click brings up the palette.

Allow to use palette colors for colourise, tint, and gradient translate.

---

src/Dialogs/TranslationEditorDialog.cpp
src/Dialogs/TranslationEditorDialog.h
src/Graphics/Palette/Palette.cpp
src/Graphics/SImage/SImage.cpp
src/Graphics/Translation.cpp
src/Graphics/Translation.h
src/MapEditor/MapEditorWindow.cpp

Among other things, this fixes #638.

Colour Remap improvements

---

src/Utility/Tokenizer.cpp

Check for comments starting without whitespace.

---

src/Archive/Archive.cpp
src/Dialogs/Preferences/GeneralPrefsPanel.cpp
src/Dialogs/Preferences/GeneralPrefsPanel.h

I just noticed my WADs folder was littered with ".bak" files, to my annoyance.

Add preference to disable backups

---

dist/res/config/games/include/things_action2.cfg
dist/res/config/games/include/things_chex1.cfg
dist/res/config/games/include/things_chex3.cfg
dist/res/config/games/include/things_doom1.cfg
dist/res/config/games/include/things_doom64.cfg
dist/res/config/games/include/things_heretic.cfg
dist/res/config/games/include/things_hexen.cfg
dist/res/config/games/include/things_strife.cfg
dist/res/config/ports/include/things_zdoom.cfg
dist/res/config/ports/zdoom.cfg
src/General/KeyBind.cpp
src/MainEditor/UI/TextureXEditor/ZTextureEditorPanel.cpp
src/MainEditor/UI/TextureXEditor/ZTextureEditorPanel.h
src/MapEditor/GameConfiguration/GameConfiguration.cpp
src/MapEditor/GameConfiguration/GameConfiguration.h
src/MapEditor/GameConfiguration/ThingType.cpp
src/MapEditor/GameConfiguration/ThingType.h
src/MapEditor/MapChecks.cpp
src/MapEditor/MapChecks.h
src/MapEditor/MapEditor.cpp
src/MapEditor/MapEditor.h
src/MapEditor/UI/MapChecksPanel.cpp
src/MapEditor/UI/MapChecksPanel.h

Fixes #393; fixes #660; fixes #702; and adds a simple feature present in GZDB.

Map editor work, mostly UI and map checks.

---

src/CMakeLists.txt

Remove Xcode specific CMake variables conflicting with Cotire

---

src/Dialogs/Preferences/ColourPrefsPanel.cpp
src/Dialogs/Preferences/TextStylePrefsPanel.cpp
src/Dialogs/TranslationEditorDialog.cpp
src/Graphics/CTexture/CTexture.cpp
src/Graphics/SImage/SImage.cpp
src/Graphics/SImage/SImage.h
src/Graphics/Translation.cpp
src/Graphics/Translation.h
src/MainEditor/UI/EntryPanel/PaletteEntryPanel.cpp
src/MapEditor/GameConfiguration/GameConfiguration.cpp
src/MapEditor/MapTextureManager.cpp
src/MapEditor/Renderer/MapRenderer2D.cpp
src/MapEditor/SLADEMap/MapSector.cpp
src/MapEditor/UI/PropsPanel/MOPGProperty.cpp
src/MapEditor/UI/PropsPanel/ThingPropsPanel.cpp
src/OpenGL/Drawing.cpp
src/OpenGL/GLTexture.cpp
src/UI/Browser/BrowserCanvas.cpp
src/UI/SAuiTabArt.cpp
src/UI/SToolBar/SToolBar.cpp
src/UI/SToolBar/SToolBarButton.cpp
src/Utility/Structs.h

Implement ZDoom texture blending

---

src/MapEditor/UI/MapCanvas.cpp

Came up with this not quite elegant solution for #676.
Works fine in low and high resolution modes on macOS.
**I cannot test it on other platforms so any feedback will be appreciated.**

Attempt to support HiDPI in 3D map view

---

src/MainEditor/MainEditor.cpp
src/MainEditor/UI/MainWindow.cpp

NO_WEBVIEW fix

---

dist/res/config/ports/include/props_eternity.cfg

Also re-ordered portal-setting properties.

Add new Eternity UDMF scroller props

---

slade.desktop
src/CMakeLists.txt

Desktop entry file for linux distros

Desktop entry for SLADE

---

src/Dialogs/Preferences/GraphicsPrefsPanel.cpp
src/MainEditor/UI/EntryPanel/GfxEntryPanel.cpp
src/MainEditor/UI/StartPage.cpp
src/MapEditor/MapEditContext.cpp
src/UI/STopWindow.cpp

This PR resolves the following issues:
sirjuddington/SLADE#812 (residual item)
sirjuddington/SLADE#813
sirjuddington/SLADE#814

Fixes for recent wxwidgets build/crash issues

---

src/Application/App.cpp
src/Application/App.h
src/General/UI.cpp

Need to keep the main thread id and not do anything with the splash window from other threads

Fix for #834

---

net.mancubus.SLADE.appdata.xml

couldn't find a good source for this other than https://github.com/hughsie/oars/issues/18

OARS 1.1 content attributes default to none

---

src/General/ResourceManager.cpp
src/General/ResourceManager.h
src/Graphics/CTexture/CTexture.cpp
src/MainEditor/UI/TextureXEditor/PatchBrowser.cpp
src/MainEditor/UI/TextureXEditor/PatchBrowser.h
src/MainEditor/UI/TextureXEditor/TextureEditorPanel.cpp
src/MainEditor/UI/TextureXEditor/TextureXEditor.cpp
src/MainEditor/UI/TextureXEditor/TextureXEditor.h
src/MainEditor/UI/TextureXEditor/TextureXPanel.cpp
src/MainEditor/UI/TextureXEditor/ZTextureEditorPanel.cpp
src/MapEditor/MapTextureManager.cpp
src/MapEditor/MapTextureManager.h
src/MapEditor/Renderer/Overlays/QuickTextureOverlay3d.cpp
src/MapEditor/UI/Dialogs/MapTextureBrowser.cpp
src/MapEditor/UI/PropsPanel/SectorPropsPanel.cpp
src/MapEditor/UI/PropsPanel/SidePropsPanel.cpp

This pull request supersedes #894 and #895, and fixes #427.

Add full path texture support to the map editor and composite texture editor

---

src/MapEditor/Renderer/MapRenderer2D.cpp

Fix memory leak in vertex mode

---

src/MapEditor/Edit/Input.cpp
src/MapEditor/MapEditContext.cpp

Remove duplicated editor messages.
Replace message strings.

Small addition to PR #928

---

src/UI/Controls/UndoManagerHistoryPanel.cpp

And some type changes/casting.

Prevent assertion in 'UndoManagerHistoryPanel.cpp'

---

src/Utility/Structs.h

* Use `<cmath>` instead of `<math.h>` and fix ambiguous calls to `sqrt`.
* Some casts and rounds here and there.

Minor changes in structs.h

---

src/MapEditor/MapEditContext.cpp
src/MapEditor/UI/MapEditorWindow.cpp

forceRefreshRenderer() needs to update the renderer when it's called.

Fix for issue #929, and maybe #918

---

src/MainEditor/UI/EntryPanel/PaletteEntryPanel.cpp
src/MainEditor/UI/StartPage.cpp
src/MapEditor/MapEditContext.cpp
src/MapEditor/UI/MapChecksPanel.cpp
src/TextEditor/UI/SCallTip.cpp
src/Utility/Parser.cpp
src/Utility/PropertyList/Property.cpp

I have searched the code with regexes after another assertion popped up,
these are the most evident ones I have found.

Prevent more assertions

---

dist/res/config/languages/acs.txt
dist/res/config/languages/zscript.txt
src/TextEditor/TextLanguage.cpp
src/TextEditor/TextLanguage.h
src/TextEditor/UI/SCallTip.cpp
src/TextEditor/UI/SCallTip.h
src/TextEditor/UI/TextEditorCtrl.cpp

I'm going to add more commits later. We can squash them after review if they are accepted.

Fix/Enhancements for text editor calltips.

---

src/Application/App.h
src/MainEditor/UI/TextureXEditor/TextureEditorPanel.cpp

Fix types for version numbers not matching the type given in the format string
Fix column span for label_scaled_size_ (must be strictly positive)

Fix a few assertion errors

---

src/UI/Lists/VirtualListView.h

Fix compilation of Linux and macOS targets

---

src/MapEditor/MapSpecials.cpp
src/MapEditor/SLADEMap/SLADEMap.cpp

Add support for reading and using UDMF plane properties in processZDoomSlopes
Add support for properly writing UDMF plane properties in writeUDMFMap

Attempt to add support for UDMF planes

---

COMPILE.md

Add basic compilation overview

---

Info.plist

Hi 👋🏻 
This is my first PR, I hope I made it the right way.
This fix is related to #1188 and #1032 issues, it doesn't fix them but at least it will makes Slade interface easy to read 😄

Opt out of dark mode for macOS

---

dist/res/config/languages/edf.txt

Remove pointless whitespace from edf.txt, add missing thingtype flags, add weapon flags, add weapon keywords, add animation keywords and flag (yes just one), add compatibility hack keywords, update font keywords, add item effect keywords, add lockdef and pickup effect keywords, add new mod keywords, add player and skin keywords, add puff keywords and flags, add switch keywords, add thinggroup keywords and flags, partially update thingtype keywords, add A_SpawnEX and its flags, add A_CounterDiceRoll and its keywords, add more codepointers.
That should be the lot for now. I may undergo a more serious full-scale effort in future to effectively "refactor" the file but this is a significant improvement in terms of feature coverage.

Update edf.txt to be be significantly more up-to-date

---

src/General/Log.cpp
src/MapEditor/ItemSelection.cpp
src/MapEditor/UI/PropsPanel/MOPGProperty.cpp
src/OpenGL/OpenGL.cpp

- Report glewInit() errors
- Flush log on write so that we don't lose log entries that can clue us into the problem if the application crashes
- Fix recent issue where special args can't be saved

Small collection of fixes

---

dist/res/config/languages/decorate.txt

It adds in a few missing functions and related constants.

DECORATE language definition update

---

src/MainEditor/UI/MainWindow.cpp
src/MainEditor/UI/TextureXEditor/TextureEditorPanel.cpp
src/MapEditor/UI/MapCanvas.cpp
src/MapEditor/UI/MapEditorWindow.cpp
src/MapEditor/UI/PropsPanel/SectorPropsPanel.cpp
src/MapEditor/UI/PropsPanel/SidePropsPanel.cpp
src/MapEditor/UI/PropsPanel/ThingPropsPanel.cpp
src/Scripting/UI/ScriptManagerWindow.cpp
src/UI/Browser/BrowserCanvas.cpp
src/UI/Browser/BrowserWindow.cpp
src/UI/Canvas/ANSICanvas.cpp
src/UI/Canvas/CTextureCanvas.cpp
src/UI/Canvas/GfxCanvas.cpp
src/UI/Canvas/MapPreviewCanvas.cpp
src/UI/Canvas/OGLCanvas.cpp
src/UI/Canvas/PaletteCanvas.cpp
src/UI/Controls/ColourBox.cpp
src/UI/Dialogs/DirArchiveUpdateDialog.cpp
src/UI/Dialogs/GfxConvDialog.cpp
src/UI/Dialogs/GfxCropDialog.cpp
src/UI/Dialogs/GfxTintDialog.cpp
src/UI/Dialogs/Preferences/PreferencesDialog.cpp
src/UI/Dialogs/TranslationEditorDialog.cpp
src/UI/Lists/VirtualListView.cpp
src/UI/SDialog.cpp

fixes #1211 and #1100
Note that I'm not sure if I was able to test everything SLADE has to offer, I simply loaded up DOOM 2 and looked at several different types of lumps and made sure they look ok on my hidpi monitor. I also may have changed things that didn't need changing, I was using grep to find where I needed to make changes based on surrounding functions.

Add initial support for HiDPI scaling, tested on an M1 Max Macbook Pro

---

dist/res/config/languages/acs.txt
dist/res/config/languages/decorate.txt
dist/res/config/languages/zdoom.txt

The highlight of this update is that it brings DECORATE up to date in terms of actor properties and flags. Though I can't promise that I didn't miss anything.

ZDoom language definitions update

---

dist/res/config/games/srb2.cfg
src/SLADEMap/MapSpecials.cpp
src/SLADEMap/MapSpecials.h
src/Utility/MathStuff.cpp
src/Utility/MathStuff.h

This also fixes Plane_align(used by zdoom) corner cases where the target line is not convex.

Add srb2 game configuration file & Srb2 slopes support

---

.github/workflows/continuous_integration.yml

Hopefully this fixes the build error

Add webkit to CI libs for linux

---

src/MainEditor/UI/StartPage.cpp

Use SetPage to load the start page on non-Windows platforms

---

dist/res/config/games/srb2.cfg
src/MapEditor/Renderer/MapRenderer3D.cpp
src/SLADEMap/MapFormat/DoomMapFormat.cpp
src/SLADEMap/MapSpecials.cpp

The only thing missing now for SLADE's map editor be fully functional for srb2 map building is 3d floors support (Floor Over Floor in srb2 terminology).

Improve srb2 support by adding remaining linedefs slopes and thing Z position editing in map editor.

---

src/SLADEMap/MapSpecials.cpp

* Improve Plane_Align correctness on sloping sectors with very "weird" geometry, now it should work for good on all cases of srb2(and any other doom source port) slopes geometries.
* Fix self-reported segmentation faults
* Defer processing of Srb2 copies slopes linedef after the other slopes linedefs to assure they don't get processed before the model sector slopes.

A bunch of Srb2 slopes fixes and improvements

---

thirdparty/CMakeLists.txt

ensure libfmt is not installed system-wide

---

dist/res/config/languages/srb2lua.txt

apologies for another PR of these, but the wiki just updated when #1578 was merged, with the fact that i discovered some syntax errors on my end a few days after.
sorry for that :P

fix srb2 lua defs

---

dist/res/config/executables.cfg
dist/res/config/ports/edge_classic.cfg
dist/res/config/ports/include/flags_edge_classic.cfg
dist/res/config/ports/include/props_edge_classic.cfg
dist/res/config/ports/include/sectors_edge_classic.cfg
dist/res/config/ports/include/specials_edge_classic.cfg
src/SLADEMap/MapSpecials.cpp
src/SLADEMap/MapSpecials.h

Initial basic configuration files and support for EC's UDMF vertex slope rendering; some of the definitions in the configs may seem redundant but since most of the stock Doom specials assume MAP_DOOM and not MAP_UDMF to be defined I had to add them as well.

Initial EDGE-Classic support

---

.github/workflows/continuous_integration.yml

Hopefully this fixes the macOS CI build

Update macOS image to macos-12 in continuous_integration.yml

---

cmake/unix.cmake

Cf. https://docs.flatpak.org/en/latest/conventions.html#application-icons

unix.cmake: Install SVG icon to standard location

---

src/Archive/Formats/RffArchive.cpp

- `0x200` - Blood Shareware Beta Build 0.91 (aka "Blood Demo"), Blood Shareware 0.99 (the initial release).
- `0x300` - Blood 1.00 (resolves #1723).
See also:
http://dukertcm.com/knowledge-base/downloads-rtcm/blood-shareware/
https://www.classicdosgames.com/game/Blood.html

Add support for versions `0x200` and `0x300` of the RFF format (Blood)
