src/ArchivePanel.cpp
This feature is extremely useful for renaming sprites and graphics (especially for me!), because it's " pain_in_ass" to rename each of ~500 and more lumps manually. I spend only 15-20 minutes for renaming 100 of them that's very very VERY annoying.
New syntax:
^ = paste alphabet letter (^^ = use lowercase characters)
% = paste alphabet repeat number  (%% = start from zero)
& = paste entry number (&& = start from zero)
How this works:
=> Added advanced file renaming syntax

CMakeLists.txt, README-unix, dist/CMakeLists.txt
If either 7z or zip programs are in path
you can now build slade.pk3 with 'pk3' target.
=> Build slade.pk3 with CMake.

src/Main.h, src/MapChecks.cpp, src/MapEditor.cpp, src/MapEditorConfigDialog.cpp, src/SLADEMap.cpp, src/SLADEMap.h, src/SectorBuilder.cpp, src/SectorBuilder.h, src/UndoRedo.cpp
Draw some architecture like this:
+-------+
|       |
|       |
|   +---+
|   |
+---+
Enter lines mode, and drag the bottom wall up and to the right so it _overlaps_ the middle wall, like this:
+-------+
\       |
\      |
+-+-+-+
Result: when you let go of mouse2, SLADE freezes for several minutes.  Once it's unfrozen, if you try to undo, the result is broken — the middle vertical wall is now two-sided, facing outwards, and _sharing a side_ with the left wall!  This is totally impossible to fix without editing the map manually; if you try to fix the side reference on either line, SLADE thinks that side index is now free for the next side you create.
It turns out I trip over this _a lot_, because I'll forget that a single solid wall is actually composed of two lines, like this: …
=> Fix for an architecture merging oversight

dist/CMakeLists.txt, src/CMakeLists.txt
Build directory can be located anywhere, not only in source directory
PK3 is placed within application bundle
Also, these changes will be required to build SLADE using Homebrew
=> Update OS X application bundle step in CMake

dist/CMakeLists.txt
PK3 may be build before executable and moving will fail as bundle directory structure isn't created yet
=> Fix parallel build via CMake on OS X

src/PakArchive.cpp
Windows is LLP64/IL32P64, most of non-Windows OSes are LP64/I32LP64
https://en.wikipedia.org/wiki/64-bit_computing
Fixes #278
=> Fix 64-bit portability issue in Pak Archive on non-Windows OSes

src/Wad2Archive.cpp, src/Wad2Archive.h
Windows is LLP64/IL32P64, most of non-Windows OSes are LP64/I32LP64
https://en.wikipedia.org/wiki/64-bit_computing
Fixes #281
=> Fix 64-bit portability issue in Wad2 Archive on non-Windows OSes

dist/res/config/ports/include/specials_zdoom.cfg, dist/res/config/ports/zdoom.cfg, src/Clipboard.cpp, src/GameConfiguration.cpp, src/MainWindow.cpp
Action specials were actually in semi-random order; they were sorted by their `index`, but due to a copying oversight, every `as_t` used to build the action special panel had an `index` of zero.  No wonder I can never find anything  :)
The easiest way to rearrange them was just to rearrange the config file, so the resulting diff is a bit of a mess.  I tried to put similar things together, and put simpler specials towards the top of the list.  I also shuffled a couple around — `Line_AlignFloor` and `Ceiling` now live in Sector alongside `Sector_SetFloorPanning` and `Sector_SetFloorScale`; `Sector_Set3dFloor` lives in the renderer section next to `Transfer_Heights`; and `Sector_Set3dMidtex` lives with the floor/ceiling specials.
=> List action specials in a more helpful order.

dist/res/config/ports/include/props_zdoom.cfg, dist/res/config/ports/include/specials_zdoom.cfg, src/ActionSpecial.cpp, src/ActionSpecial.h, src/ActionSpecialDialog.cpp, src/Args.h, src/GameConfiguration.cpp, src/GameConfiguration.h, src/ThingInfoOverlay.cpp
I added some config syntax for reusing arg definitions, since a number of them are shared between specials, and adding `custom_flags` blocks would've made for a whole lot of copy/paste.  It looks like this:
```
arg foo
{
name = "Foo";
type = bar;
}
special 123
{
name = "Sector_DoThing";
arg1 = $foo;
}
```
I also added "speed" as an arg type with a slider, and labeled it relative to the Boom generalized speeds — I always have to look them up and they are pretty good milestones.
Then I went on a wild arg-defining spree: speed of floors and doors, crush mode, means of death, and every other flag type I could find where the flags were defined in the arg description.
----
I also moved UDMF flags related to special activation onto the Special tab — I very frequently discover the hard way that …
=> More work on specials and their arguments

src/SLADEMap.cpp, src/SectorBuilder.cpp, src/SectorBuilder.h
This fixes every drawing problem I've encountered.  Most notably, drawing an "inside-out" box in the middle of a hallway (touching both sides) now creates a door sector ready to go, as you might expect.
Commits explain some other operations that didn't work before but do now.
=> Some more architecture fixes

src/MapCanvas.cpp, src/MapEditor.cpp, src/MapLine.cpp, src/MapRenderer3D.cpp, src/MapSector.cpp, src/MapSector.h, src/MapSpecials.cpp, src/MapSpecials.h, src/SLADEMap.cpp, src/SLADEMap.h
I realized there's already a mechanism that marks the end of an edit and the return of control to the user — the undo manager.  So now we just recompute slopes in bulk on map read, on undo/redo, and in `endUndoRecord`.
I timed this on Sunder's MAP14 and it adds about a quarter of a second to every edit on my machine.  Could be improved (indexed blockmap of object positions, perhaps?), but many simple geometry edits on that map take _multiple_ seconds, so.
tl;dr:
- Vavoom slope things, vertex height things, and `Plane_Copy` now work.
- Pasting no longer crashes.
- Opening a map and switching to 3D mode no longer sets it as modified.
- 3D mode should now always highlight the correct wall; previously the cursor could mistakenly think it was pointing at some oddly-shaped sloped walls. …
=> Actually finish slope support

src/MIDIPlayer.cpp
An attempt to fix this issue: https://github.com/sirjuddington/SLADE/issues/309
=> Fixed invalid use of wxProcess in MIDIPlayerApp

src/ActionSpecialDialog.cpp, src/DirArchive.cpp, src/STabCtrl.cpp, src/STabCtrl.h
This fixes #231.  Also, I hate wxWidgets.
Curiously, this same change applied to master results in an archive manager panel that refuses to go any narrower than half the width of my screen _and_ puts the two lists next to each other rather than stacked.  I'm guessing bf6d8e0a is why, but the different orientation baffles me.
From commit, for your convenience:
----
I only barely understand what is going on in most of this but this makes sizing work more better.
- `wxDataViewTreeCtrl`, used to show the list of action specials, doesn't really report a minimum size very well.  I had to manually compute the size of each of the specials' names to get the minimum width correct.
- Sometimes parts of the fancy arg controls (flag names and the like) got cut off.  Needed to explicitly recompute the …
=> Fix a bunch of sizing stuff with the action special panels

src/MapRenderer3D.cpp, src/MapRenderer3D.h, src/MapSector.cpp, src/MapSector.h, src/MapSpecials.cpp, src/MapSpecials.h, src/SLADEMap.cpp
What changed:
- Removed default global fog, added custom fog which can be configured from UDMF (fade color) or ACS scripts (Sector_SetFade).
- Fixed some sector/line update issues with color/fog in "checkVisibleFlats".
- Added new CVAR render_fog_distance (default: 1000)
Fog enabled:
Fog disabled:
=> Added basic level fog preview

src/EntryOperations.cpp
Print all messages from compiler stderr (and stdout) if acc.err doesn't exists. (prints both to the console by default)
https://github.com/sirjuddington/SLADE/issues/335
=> EntryOperations fix

src/BrowserItem.h, src/CTexture.h, src/MCAnimations.h, src/MCOverlay.h, src/Translation.h, src/zreaders/i_musicinterns.h
Clang produced the following list of warnings:
```
src/CTexture.cpp:428:3: warning: delete called on 'CTPatch' that has virtual functions but non-virtual destructor [-Wdelete-non-virtual-dtor]
src/CTexture.cpp:548:3: warning: delete called on 'CTPatch' that has virtual functions but non-virtual destructor [-Wdelete-non-virtual-dtor]
src/CTexture.cpp:590:2: warning: delete called on 'CTPatch' that has virtual functions but non-virtual destructor [-Wdelete-non-virtual-dtor]
src/CTexture.cpp:615:4: warning: delete called on 'CTPatch' that has virtual functions but non-virtual destructor [-Wdelete-non-virtual-dtor]
src/CTexture.cpp:892:3: warning: delete called on 'CTPatch' that has virtual functions but non-virtual destructor [-Wdelete-non-virtual-dtor]
src/CTexture.cpp:925:3: warning: …
```
=> Fixed memory leaks in polymorphic types

src/ActionSpecialDialog.cpp, src/Clipboard.cpp, src/Clipboard.h, src/GenLineSpecialPanel.cpp, src/KeyBind.cpp, src/MapCanvas.cpp, src/MapEditor.cpp, src/MapEditor.h, src/MapEditorWindow.cpp, src/MapLine.h, src/MapRenderer3D.cpp, src/MapSide.cpp, src/MapSide.h, src/MapTextureManager.cpp, src/SLADEMap.cpp
Some more small, mostly-independent things.  Also includes a possible fix for the crash in #366.
=> Fix some more papercuts

src/ArchiveManager.cpp, src/CMakeLists.txt, src/Main.h, src/MainApp.cpp
I've created install targets for non-OSX builds that moves the `slade` binary into `$PREFIX/bin` and `slade.pk3` into `$PREFIX/share/slade3` (to be consistent with `wxStandardPaths::GetResourcesDir()`). I've intentionally ignored OSX and WIN32 because of the former's different way of doing things that I'm not familiar with, and the latter will generally be using a more full-fledged installer anyways.
I've also expanded the search for `slade.pk3` to look in the resources directory (`wxStandardPaths::GetResourcesDir()`) before moving on. If INSTALL_PREFIX (provisioned from CMAKE_INSTALL_PREFIX) is defined, then we'll need to pass that into `wxStandardPaths::SetInstallPrefix()` so that the resources directory is adjusted accordingly. This should be pretty standard and useful across Linux/BSD …
=> (UNIX) Create install targets, expand search space for slade.pk3

src/Dialogs/Preferences/BaseResourceArchivesPanel.cpp, src/Dialogs/Preferences/BaseResourceArchivesPanel.h, src/Dialogs/SetupWizard/BaseResourceWizardPage.cpp
Now there's a button to do it on the panel, instead of it being called
everytime the panel is created. It's also called by the setup wizard.
=> Tweak calls to archive autodetect

src/CMakeLists.txt, src/Main.h
Xcode attributes are ignored by other CMake generators
I don't have any other setup for building SLADE except OS X.
So I cannot add precompiled header support for other platforms.
=> Added prefix header for generated Xcode project

src/Drawing.cpp, src/Drawing.h, src/InfoOverlay3d.cpp, src/Main.h, src/MapCanvas.cpp, src/MapChecks.cpp, src/MapEditor.cpp, src/MapLine.cpp, src/MapLine.h, src/MapRenderer3D.cpp, src/MapSector.cpp, src/MapSector.h, src/MapSpecials.cpp, src/MapThing.cpp, src/MapThing.h, src/MapVertex.cpp, src/MapVertex.h, src/MathStuff.cpp, src/MathStuff.h, src/ObjectEdit.cpp, src/ObjectEdit.h, src/Polygon2D.cpp, src/Polygon2D.h, src/SLADEMap.cpp, src/SLADEMap.h, src/SectorBuilder.cpp, src/Structs.h, src/ThingPropsPanel.cpp
A humble proposal.  We've already got `fpoint2_t` and friends, but there's a lot of code that still handles and passes points around as distinct `x` and `y` coordinates, which strikes me as tedious and error-prone.  So I changed some of it to work with points instead, and added a couple helper methods to map objects.
I also threw in a `LOG_DEBUG`, because trying to get C++ to do useful print-debugging has been driving me up the wall.  You can tell any type how to cast itself to `Debuggable` and it'll print out to the console that way when you feed it to `LOG_DEBUG`, no format strings or other nonsense required.  And it all compiles out in production builds.  I changed the logging in `SLADEMap::cutLines` to use it as an example, since it's especially un-useful to end users.
I know this is …
=> Use the point types more heavily

src/Main.h
Non-Windows versions will be broken otherwise.
=> Fixed non-MSVC compilation

src/CMakeLists.txt
Incorrect path to prefix header led to build failure on OS X after rearrangement in files/directories structure
=> Adjusted path to Xcode prefix header

src/Application/MainApp.cpp, src/CMakeLists.txt, src/Dialogs/RunDialog.cpp
Adjusted path to Xcode prefix header
Set install prefix only for wxGTK targets
Generic way to get executable path from bundle
=> OS X fixes for stable branch

src/Application/MainApp.cpp
This resolves the problem I've mentioned as a comment in #333.
If SLADE is running and a new instance is started without arguments it stays open otherwise it sends the arguments to the first instance and closes the second. This mimics the behavior of VLC.
Disclaimer: I've only tested the changes with the 3.1.1.1 release because master currently doesn't compile on my end.
=> Allow multiple instances if the new ones are started without arguments (Fixes issues created by #333)

src/Application/Main.h
This fixes #497.
Relying on `WXDEBUG` meant that the non-debug code was only used when the wx library had been built in non-debug mode, regardless of how SLADE was built.
Also, the non-debug code didn't have a constructor that took any arguments, hence the compile errors.
=> Fix Debuggable in release mode

src/UI/TextEditor/SCallTip.cpp
wxWindow::SetDoubleBuffered() isn't available on OS X
=> Fixed compilation on OS X

dist/res/config/iwads.cfg
This would cause SLADE to crash on Windows (and likely Linux/OSX, however I didn't test on those).
=> iwads.cfg: Fix erroneous colon for the GOG strife WAD path

src/MapEditor/GameConfiguration/GameConfiguration.cpp
Do the null check before the dereference.
=> GameConfiguration: Amend if statement null checking order

src/Utility/PropertyList/Property.cpp
Previously this was just reassigning the parameter.
=> Property: Fix error case for invalid types in the constructor

src/UI/TextEditor/TextEditor.cpp
Opening ZDoom Texture Definitions lump no longer leads to a crash
=> Fixed crash when opening lump in text editor

dist/res/config/ports/include/specials_eternity.cfg
Previously all lines that were >400 were not in the config. They are now accounted for.
On top of this ExtraData specials have their own little group, and special 307's description was changed to reflect its current name.
=> Updated the Eternity config to have parity with the more recent Eternity builds.

dist/res/config/entry_types/types_text.txt, src/Archive/ArchiveEntry.h, src/Archive/Formats/HogArchive.cpp
HogArchive writing was completely broken and forced upper case for no reason (original data files are lower case).  Also handled briefing file encryption (otherwise they're just text files) at the archive level to increase general usefulness without much of an increase to complexity.
=> HogArchive improvements

dist/res/config/entry_types/types_text.txt
This one commit just adds soc to the list of text types, so it gets
recognized as a SOC and not (Unknown) in SLADE.
=> Allow editing of SOC lumps in the text editor.

build/msvc/SLADE.vcxproj, build/msvc/SLADE.vcxproj.filters
Old settings for a few headers didn't reference the correct directories, missing out the fact that some of the files were in the "External" folder. Ignore the branch name; I'm working on a new feature and this commit precedes my work on that.
=> Fix MSVC always recompiling

build/msvc/SLADE.vcxproj, build/msvc/SLADE.vcxproj.filters, dist/res/config/languages/0_base.txt, dist/res/config/languages/decorate.txt, dist/res/config/text_styles/0default_dark.sss, dist/res/config/text_styles/default.sss, dist/res/config/text_styles/material.sss, dist/res/config/text_styles/old_dark.sss, dist/res/config/text_styles/old_default.sss, src/Dialogs/Preferences/PreferencesDialog.cpp, src/Dialogs/Preferences/TextEditorPrefsPanel.cpp, src/Dialogs/Preferences/TextEditorPrefsPanel.h, src/Dialogs/Preferences/TextStylePrefsPanel.cpp, src/MapEditor/UI/ScriptEditorPanel.cpp, src/UI/TextEditor/Lexer.cpp, src/UI/TextEditor/Lexer.h, src/UI/TextEditor/TextEditor.cpp, src/UI/TextEditor/TextEditor.h, src/UI/TextEditor/TextLanguage.cpp, src/UI/TextEditor/TextLanguage.h, src/UI/TextEditor/TextStyle.cpp, src/Utility/Parser.cpp
Added a custom lexer implementation for the text editor, does everything the standard one did before but with the following benefits:
- Comment, preprocessor and block start/end tokens are now configurable via TextLanguage
- Allow more word lists to be defined for syntax highlighting (added 'Type' and 'Property' word lists configurable via TextLanguage, in addition to the existing keyword/constant/function lists)
- Improved code folding in some situations, eg. having a block opening `{` on a line on its own will fold from the line above instead
Other improvements and additions:
- Added (optional) highlighting of all occurrences of the word under the cursor
- Added (optional) highlight for current line
- Added new styles for 'Comment (Doc)', 'Type', 'Property', 'Word Match' and 'Current …
=> Improved Text Editor syntax highlighting (and more) via custom lexer

dist/res/config/ports/eternity.cfg, dist/res/config/ports/zdoom.cfg, src/MapEditor/GameConfiguration/GameConfiguration.cpp, src/MapEditor/GameConfiguration/GameConfiguration.h, src/MapEditor/MapEditor.cpp, src/MapEditor/Renderer/MapRenderer2D.cpp, src/MapEditor/Renderer/MapRenderer3D.cpp, src/MapEditor/Renderer/MapRenderer3D.h, src/MapEditor/Renderer/Overlays/InfoOverlay3d.cpp, src/MapEditor/SLADEMap/MapSector.cpp, src/MapEditor/SLADEMap/MapSide.cpp
This makes it so that a great deal of features that ZDoom and Eternity UDMF have are not hard-coded string checks against the namespace. Instead they are delegated to the config files. This avoids code duplication, and provides an example of what can be done in future to avoid code duplication when EE or ZDoom get their own specific UDMF features that work their way into being rendered.
A couple things still are hard-coded though.
=> Remove hard-coding of a wealth of UDMF rendering features

src/CMakeLists.txt
C++11 has to be specified to compile on Debian/Unix. This works in jessie and stretch, and should work for other systems as well.
Presumably fixes #627.
=> Require C++ 11 in cmake

src/UI/TextEditor/SCallTip.cpp, src/UI/TextEditor/SCallTip.h
Not sure exactly if it's an osx or dpi issue, but wx isn't scaling the calltip bitmap correctly when drawing it
=> Fix calltip drawing on osx with high dpi

dist/res/config/ports/include/things_zdoom.cfg
Ambient Sound \#30 (Thing ID 14030) was configured as thing 14020.
=> Fix small typo in things_zdoom.cfg

build/msvc/SLADE.vcxproj, src/Archive/Archive.cpp, src/Archive/ArchiveEntry.h, src/Graphics/SImage/SIFormat.cpp, src/MainEditor/UI/EntryPanel/DataEntryPanel.cpp, src/MainEditor/UI/EntryPanel/TextEntryPanel.cpp, src/Utility/Tokenizer.h
* Fixed warnings about signed/unsigned mismatch by changing to unsigned a few values that are only ever assigned or compared to unsigned values, yet were signed for some reason.
* Fixed TextEntryPanel's event handler missing the check about whether it was the active panel. Among other annoyances, it made impossible to do a search & replace operation on a different tab than the first.
* Added some commented-out stuff about the Strife demo conversation script format. It's more for documentation than anything else, which is why it's commented out.
=> Various fixes

cmake/cotire.cmake, src/CMakeLists.txt
The pch generated by cotire was ignored because of sakra/cotire#94 and because cotire must be added after all target properties of the executable have been set.
The second commit isn't part of the fix but may save some trouble someday.
=> Fix pre-compiled header in cmake

src/Dialogs/Preferences/PreferencesDialog.cpp
Unfortunately, SLADE will never be free of crashes (it already crashes a bit more frequently than I'm sure everyone would like it to), which cause the user to have to redo any changes to their config since the last boot.
I don't know if you have any specific thoughts on the issue, but this seems like a pretty satisfying solution to me.
=> Save config file when applying preferences

src/General/ResourceManager.cpp, src/MapEditor/SLADEMap/MapSector.cpp
Basically, the resource manager is notified when entries of an archive are changed, including directories, but in `ResourceManager::onAnnouncement` it does some indirection which looks like
```
entry->getParent()->entryAtPathShared(entry->getPath(true));
```
This only works on file entries, not directories, because directories don't show up as entries in the archive tree, i.e. `entryAtPath` doesn't "see" directories and so returns null causing an error. It's pretty confusing that directories are treated as entries in some contexts but not in others.
Also fixes a bug left behind in a previous PR.
=> Fix crash on saving ZIP archives

src/Graphics/CTexture/CTexture.cpp
When values were in three separate parameters, they were read as if they were on a 0.0-1.0 scale, instead of the 0-255 scale they actually are. The operation of multiplying them by 255 and then forcing them back into a single byte inverted their values (except for 0 and 128). Fixes the actual bug of #693.
=> Fix improper parsing of RGB values in patch blends.

src/UI/Canvas/GfxCanvas.h
After trying to compile SLADE with Clang 3.8.1, I got this compilation error:
/src/MainEditor/UI/EntryPanel/GfxEntryPanel.cpp: In member function ‘virtual bool GfxEntryPanel::handleAction(string)’:
/src/MainEditor/UI/EntryPanel/GfxEntryPanel.cpp:729:50: error: invalid initialization of non-const reference of type ‘rgba_t&’ from an rvalue of type ‘rgba_t’
gfx_canvas->setPaintColour(cb_colour->getColour());
~~~~~~~~~~~~~~~~~~~~^~
In file included from /src/MainEditor/UI/EntryPanel/GfxEntryPanel.h:6:0,
from /src/MainEditor/UI/EntryPanel/GfxEntryPanel.cpp:31:
/src/./UI/Canvas/GfxCanvas.h:93:7: note:   initializing argument 1 of ‘void GfxCanvas::setPaintColour(rgba_t&)’
void setPaintColour(rgba_t &col) { paint_colour.set(col); }
^~~~~~~~~~~~~~
/src/MainEditor/UI/EntryPanel/GfxEntryPanel.cpp: …
=> Fix non-const reference argument

CMakeLists.txt, cmake/FindFTGL.cmake, cmake/FindGLEW.cmake, src/CMakeLists.txt, src/External/CMakeLists.txt
I've never done unity builds before, so I was pretty confused at first and thought it would be too complicated to get working, yet it turned out to be pretty easy once I actually figured it out.
External sources must be compiled as a separate step since they do things like use static declarations, which are incompatible with this technique. Other than that, all that had to be changed was to undefine a dumb macro that bled all the way over from an X11 include file.
cotire generates a target called `slade_unity` which produces and compiles the unity source file. If you just run `make`, it will do an incremental compilation instead (maybe good if you only change a few files at once during development).
The difference wasn't as noticeable during a parallel build, which is already pretty fast, …
=> Unity builds

src/Dialogs/RunDialog.cpp
I think the Run dialog will be a little easier to use if the "Run" button is selected by default. This way when it pops up, pressing enter will cause the game to start.
=> Make Run button in Run dialog the default button

src/General/KeyBind.cpp, src/UI/TextEditor/TextEditor.cpp, src/UI/TextEditor/TextEditor.h, src/UI/TextEditor/TextLanguage.cpp
**Supersedes #753**
I have squashed the commits and I have made the pull request from a proper branch this time.
Sorry for this mess.
**Original comment:**
I finally ended up working in my own request #746
There are two new commands for the text editor:
· Line Comment
Default bind = Ctrl + /
If there's no selection a simple line comment // is added to the line the caret is on. If there's a comment in the current line, it's cleared. Then the caret jumps to the next line.
If there's a block of text selected the command will act upon all the lines that have a character selected.
· Block Comment
Default bind = Ctrl + Shift + /'
It wraps the selected text on block comments /* text */
If the selection begins with /*, and ends with */, the comment will be cleared.
Let me know if there's …
=> Text editor commands to comment/uncomment code.

src/MapEditor/SLADEMap/SLADEMap.cpp, src/common.h
Fixes #759:
There was a typo in `SLADEMap.cpp`
Fixes #758:
The `<functional>` header could not be found by the compiler while processing `SScriptDialog.cpp`
I have added it in `scr/common.h` but don't know if that's the place you want to put it.
=> Fix gcc build errors.

src/Game/ZScript.cpp
64-bit target has 4 bytes int and 8 bytes long types which cause the following compilation error:
```src/Game/ZScript.cpp:621:93: error: non-constant-expression cannot be narrowed from type 'long' to 'int' in initializer list [-Wc++11-narrowing]```
=> Fixed compilation with Clang

src/Application/SLADEWxApp.cpp
wxMemoryDC::GetPPI().x from wxWidgets 3.1 is equal to 72 which led to weird 75% scaling on macOS
=> Fixed UI scaling on macOS

net.mancubus.SLADE.appdata.xml, net.mancubus.SLADE.desktop, src/CMakeLists.txt
This adds an [AppData](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps) file, which makes applications look better in Gnome Software & KDE Discover.
Also, this changes the ID of the desktop file to use the same reverse domain name notation.
=> Add appdata

dist/res/config/ports/include/props_zdoom.cfg
Fixed a typo where the “moreids” property was actually called “modeids"
=> Fixed “modeids” typo

dist/res/actions/txed.cfg
"Export Texture" really converts a composite texture to a single patch, and "Extract Texture" exports composite textures to PNG files. I also used "Patch" and "PNG file" because these menu items were on a submenu titled "Export To".
This pull request is on master rather than stable, and changes a config file rather than the code.
=> Make txed_{export,extract} texts match their functions

src/MainEditor/Conversions.cpp
DPBSPWLK (DOOM2.WAD, etc) is 8 bytes, 4 samples
=> Allow conversion of DPBSPWLK to wav

src/Application/SLADEWxApp.h, src/Audio/AudioTags.cpp, src/External/zreaders/files.cpp, src/MainEditor/EntryOperations.cpp, src/MainEditor/ExternalEditManager.cpp, src/MainEditor/UI/ArchivePanel.h, src/MainEditor/UI/EntryPanel/AudioEntryPanel.cpp, src/MapEditor/MapEditContext.cpp, src/MapEditor/SLADEMap/SLADEMap.cpp, src/TextEditor/UI/TextEditorCtrl.cpp
There are several warnings detected by Clang on macOS. The ones trivial to fix are solved in this pull request. The others (such as unused variables – lots of them – or deprecated OpenGL calls) seem the result of deliberate coding, so I didn't touch them.
=> Fix minor compiler warnings

src/MainEditor/Conversions.cpp
account for internal headers in size field (assuming only 2 chunks)
=> fix WAV RIFF header reported size

src/MapEditor/UI/MapEditorWindow.cpp
Make the status bar fields wider so there's enough room to display large numbers.
160 pixels is not enough for the coordinates field, specially in UDMF maps due to the three decimal places.
Current widths:
Proposed width:
=> Map Editor: Equalize status bar field widths

src/Dialogs/Preferences/AdvancedPrefsPanel.cpp, src/Dialogs/Preferences/ColourPrefsPanel.cpp, src/MapEditor/UI/PropsPanel/MapObjectPropsPanel.cpp
By default, wxWidgets doesn't use the current theme's inactive text color for the wxPropertyGrid widget. If a dark theme is being used, inactive labels become unreadable, since they will use black text with a dark background.
None of the main branches seem to build with GTK3. Since this change is specific to GTK3's theme functionality, I made the commit in the gtk3 branch.
=> Force inactive text colour in wxPropertyGrid

dist/CMakeLists.txt
Quick fix for #903, `-mtu+` option is not recognized by 7z.
=> Update CMakeLists.txt for quick fix of #903

src/MapEditor/Edit/Input.cpp, src/MapEditor/MapEditContext.cpp, src/MapEditor/UI/MapCanvas.cpp
I noticed SLADE was using a lot of idle CPU regardless of whether or not the application was active. I use it a lot on my laptop so it's important to conserve battery life. This patch makes it so that the map editor only redraws on user input or when an animation is active. The "map_bg_ms" cvar was somewhat useless before so it has been changed so that it controls FPS for the map canvas. Ideally for smooth performance this setting should default to the screen refresh rate, but wxWidgets doesn't have a facility for that. I left it in so that people with slow machines can set it higher in case of GL hiccups.
This should clear up some of the CPU usage issues described in #876, but it seems there is also a memory leak somewhere, which is a separate issue. If someone would like to test this …
=> Don't redraw map editor when application is idle

src/TextEditor/TextLanguage.cpp, src/TextEditor/TextLanguage.h
Do not clear the function name before replacing it's contexts.
Fixes #905
=> Fix for issue #905

src/Utility/Tokenizer.cpp, src/Utility/Tokenizer.h
* Do not increment `state_.current_line` if a token is ended at a newline
Currently if that's the case, 'current_line' is incremented twice.
This makes the text editor jump points to misbehave in files with a
code style like this:
```
1   function void
2   function_name ()
3   {
4     ...code...
5   }
6
7   if (test)
8   {
9     ...code...
10  }
11  else
12  {
13    ...code...
14  }
```
`state_.current_line` is incremented twice at lines 1 and 11
* Remove default case in switch statement, all possible cases are dealt
with
* Use the more robust `wxFileOffset` and `size_t` types where appropriate
* Make some implicit casts explicit
=> Tokenizer improvements.

src/Game/Game.cpp
It's possible for a `zdoom.pk3` archive to not contain a `zscript.txt` file.
Check if we have obtained a valid entry and throw a warn if not.
=> Prevent crash if no 'zscript.txt' entry found.

src/MapEditor/MapEditContext.cpp, src/MapEditor/UI/MapEditorWindow.cpp
The map editor 2d mode has been acting funny since 6029370232c8fd22f624e51c17c71b3a6eec06e2
This forces the map view to update after changing the flat render type or the sector mode.
=>  Map Editor: Force the renderer to refresh.

src/General/Console/Console.cpp
ASSERT INFO:
/usr/include/wx-3.0/wx/strvararg.h(456): assert "(argtype & (wxFormatStringSpecifier<T>::value)) == argtype" failed in wxArgNormalizer(): format specifier doesn't match argument type
BACKTRACE:
[1] wxArgNormalizer<unsigned long>::wxArgNormalizer(unsigned long, wxFormatString const*, unsigned int)
[2] wxArgNormalizerWchar<unsigned long>::wxArgNormalizerWchar(unsigned long, wxFormatString const*, unsigned int)
[3] wxString wxString::Format<wxString, unsigned long>(wxFormatString const&, wxString, unsigned long)
[4] c_cmdlist(std::vector<wxString, std::allocator<wxString> >)
[5] ConsoleCommand::execute(std::vector<wxString, std::allocator<wxString> >)
[6] Console::execute(wxString)
[7] ConsolePanel::onCommandEnter(wxCommandEvent&)
[8] …
=> Prevent assert in cmdlist console command

src/MapEditor/MapTextureManager.cpp
Composite textures take precedence over the textures/ directory
Flats also use extended (ZDoom TEXTURES) composite textures over flats in the flats/ directory or between the F_START/F_END lumps
[Demo](http://www.ciinet.org/kevin/myimages2/doom/bugtests/PBR3DFloor.zip)
=> Attempt to fix texture usage precedence

dist/res/config/ports/include/props_zdoom.cfg
This includes the [new properties](https://github.com/coelckers/gzdoom/commit/f2dcff43868b2cf34f7b69e677a32b76724b02b3) for Doom 64-style lighting, as well as the lightmap-related properties used by [ZDRay](https://github.com/dpJudas/ZDRay).
=> Add the recently-added GZDoom UDMF properties

CMakeLists.txt
CMP0072
-------
``FindOpenGL`` prefers GLVND by default when available.
The ``FindOpenGL`` module provides an ``OpenGL::GL`` target and an
``OPENGL_LIBRARIES`` variable for projects to use for legacy GL interfaces.
When both a legacy GL library (e.g. ``libGL.so``) and GLVND libraries
for OpenGL and GLX (e.g. ``libOpenGL.so`` and ``libGLX.so``) are available,
the module must choose between them.  It documents an ``OpenGL_GL_PREFERENCE``
variable that can be used to specify an explicit preference.  When no such
preference is set, the module must choose a default preference.
CMake 3.11 and above prefer to choose GLVND libraries.  This policy provides
compatibility with projects that expect the legacy GL library to be used.
The ``OLD`` behavior for this policy is to set …
=> Set CMP0072 NEW behabiour

dist/res/config/ports/include/props_zdoom.cfg
Horizontal scale appeared as vertical scale, and vice versa.
=> Fix swapped horizontal/vertical scale

src/MapEditor/Edit/Edit2D.cpp
Now that the sector is deleted in removeSide, the sector no longer needs to be deleted in deleteSector, since deleteSector calls removeSide, which in turn causes sectors without sidedefs to be deleted, resulting in two sectors being deleted.
This commit removes the sector deletion code from deleteSector, instead delegating it to removeSide.
=> Fix sector deletion in sector mode

src/MapEditor/MapTextureManager.cpp, src/MapEditor/Renderer/MapRenderer3D.cpp, src/OpenGL/GLTexture.cpp, src/OpenGL/GLTexture.h
Fix UV coordinates and scale for quads that use scaled textures.
Set sx and sy to the scale specified in the texture definition.
Add world_panning field to GLTexture so that the "World panning" flag is passed to the renderer, and set it in MapTextureManager.getTexture/getFlat.
Use GLTexture worldPanning to determine how UVs of quads should be manipulated.
Don't scale UVs in setupQuadTexCoords
I tested my changes on [Final NeoDoom](https://forum.zdoom.org/viewtopic.php?f=19&t=49090&hilit=NeoDoom#p848714) MAP06, which has several road signs made from midtextures.
=> Fix UV coordinates and scale of scaled textures

src/CMakeLists.txt
This variable does already get used by find_package(wxWidgets...), this
ensures that the additional version checks do also use the correct
wx-config executable and also makes it possible to change the wx-config
executable with only one switch
=> Use wxWidgets_CONFIG_EXECUTABLE in cmake when it is set

dist/res/config/languages/acs.txt
* New function definitions for `SetActivatorToPlayer` and `SetDeadEspectator`
Fixes #925
=> Add support for new Zandronum only ACS functions

src/MainEditor/UI/TextureXEditor/TextureXPanel.cpp
This makes copying and pasting textures from one archive to another work, as well as exporting PNGs or patches from TEXTURE2 work.
=> Use current page check in addition to visibility check

src/Dialogs/Preferences/BaseResourceArchivesPanel.cpp
The loop change in src/Dialogs/Preferences/BaseResourceArchivesPanel.cpp forgot the non-win32 lines, this lets me build again.
Also removed an unnecessary #else, no functional change.
=> Fix compilation ifndef WIN32

src/UI/Browser/BrowserItem.cpp
This will make full path textures appear with shortened folder names. For example, textures/aquatex/aqconc13.png will appear as t./a./aqconc13.png
=> Add a more readable method of truncating full paths

CMakeLists.txt, src/CMakeLists.txt
GLib dependency must be handled by FluidSynth itself
pkg-config is no longer needed
WX_GTK3 is unusable on macOS
=> Remove pkg-config and GTK/GLib requirement on macOS

src/MapEditor/UI/ScriptEditorPanel.cpp
Name the lumps "SCRIPTS" and "BEHAVIOR" respectively, regardless of whether or not they are Hexen or ZDoom ACS scripts. If any special cases need consideration, they can be added in later, with "SCRIPTS" and "BEHAVIOR" as the default lump names.
=> Attempt to fix blank SCRIPTS/BEHAVIOR lump names

src/Graphics/SImage/SImageFormats.cpp
This PR fixes a buffer overrun that leads to heap corruption and eventual crash when opening DBIGFONT files
=> Fix crash when opening DBIGFONT files

src/MainEditor/UI/EntryPanel/GfxEntryPanel.cpp
Viewing multi-image graphic entries (e.g. .ART files in DUKE3D.GRP) makes the buttons move around unexpectedly in the bottom panel of the entry preview screen, sometimes putting the next/prev image buttons out of reach. This PR fixes this problem.
=> Fix misaligned next/prev image buttons for multi-image graphics entries

src/MainEditor/Conversions.cpp, src/MainEditor/Conversions.h, src/MainEditor/UI/ArchivePanel.cpp, src/MainEditor/UI/ArchivePanel.h
This pull request adds an option to convert Ken Silverman's .VOX voxel modes to .KVX models, that are supported by ZDoom.
=> Add .VOX -> .KVX voxel conversion

Info.plist
* Case of executable filename on disk and in Info.plist must match. Digital signature process will fail otherwise
* Do not switch GPU by default. This requires custom change to wxWidgets, see alexey-lysiuk/slade-macos-build@ccbd0b6a48fb2540f70bdb441b20e4ecfeccd4aa, as there is no support for user specified OpenGL pixel format attributes yet. Without this feature the entry has no effect, although it will be needed if such support will be added in the future
=> Fix minor issues in Info.plist

dist/res/config/ports/include/sectors_zdoom.cfg
This allows GLSector_Skybox and GLSector_NoSkyDraw to show up in the editor as valid special sector types.
=> Add GL sector specials to ZDoom configuration

src/Utility/FileUtils.cpp, src/Utility/FileUtils.h
Because `FileUtil::copyFile()` does not actually overwrite existing files, the temp file is not updated on save. `ZipArchive::save()` copies unchanged entries from the temp file, which leads to loss of earlier changes, and duplicate/invalid entries if entry ZipIds have changed on earlier saves.
=> Fix ZIP archive corruption caused by not overwriting the temp file

dist/res/config/ports/include/props_zdoom.cfg
Slope properties will now show up in the list of properties at the side. Note that this doesn't fix saving slopes in UDMF maps; that's a completely different issue.
=> Fix "Slopes" property group

thirdparty/CMakeLists.txt
Some distributions default to building libraries under CMake as
shared, which breaks in this particular case so be explicit.
=> Explicitly build "external" library as STATIC

src/CMakeLists.txt
FreeType may be used by FTGL but it's not directly used by this project. pkg-config should handle this for static builds.
=> Drop FreeType dep and only require FTGL when USE_SFML_RENDERWINDOW is disabled

src/Utility/MemChunk.cpp
Something has passed nullptr to memcpy. (This probably happens upon
first allocation.) Avoid this, it is undefined behavior.
ASAN/UBSAN reported:
MemChunk.cpp:125:9: runtime error: null pointer passed as
argument 2, which is declared to never be null
/usr/include/bits/string_fortified.h:34:33: runtime error:
null pointer passed as argument 2, which is declared to never be null
=> util: do not pass nullptr to memcpy

src/Archive/Formats/TarArchive.cpp
magic.header is treated like a C string, but if there is no \0 in the
buffer, there is your classic read-past-the-end bug.
ERROR: AddressSanitizer: stack-buffer-overflow on address [..]
READ of size 262 at 0x7ffd5e27b480 thread T0
f0 (/usr/lib64/libasan.so.5+0x67617)
f1 in std::char_traits<char>::length(char const*) /usr/include/c++/8/bits/char_traits.h:320
f2 in std::basic_string_view<char, std::char_traits<char> >::basic_string_view(char const*) /usr/include/c++/8/string_view:100
f3 in slade::TarArchive::isTarArchive(slade::MemChunk&) src/Archive/Formats/TarArchive.cpp:523
f4 in TarDataFormat::isThisFormat(slade::MemChunk&) src/Archive/EntryType/DataFormats/ArchiveFormats.h:171
f5 in slade::EntryType::isThisType(slade::ArchiveEntry&) src/Archive/EntryType/EntryType.cpp:201
f6 in …
=> archive: fix read-past-end when analyzing .wad as a .tar

src/MainEditor/UI/StartPage.cpp, src/UI/Dialogs/RunDialog.cpp
StartPage.cpp: In member function ‘void slade::SStartPage::load(bool)’:
StartPage.cpp:345:7: error: ‘std::__cxx11::string’ {aka ‘class
std::__cxx11::basic_string<char>’} has no member named ‘Replace’;
did you mean ‘replace’?
html.Replace("#recent#", recent);
Fixes: #1169
=> build: resolve compile error stemming from use of wrong types

src/Archive/Formats/TarArchive.cpp
Address two missed spots.
Fixes: #1172
=> archive: fix read-past-end when analyzing .wad as a .tar (2) (#1172)

src/CMakeLists.txt
=> build: use pkgconfig to locate and require specific fmt version (#1168)

src/Application/App.cpp, src/CMakeLists.txt, src/MainEditor/UI/ArchivePanel.cpp, src/MainEditor/UI/MainWindow.cpp, src/MapEditor/UI/MapEditorWindow.cpp
sol.hpp has a lot of templates which, when building with -g
-fsanitize=address -fsanitize=undefined, incur long compile time and
high memory usage (~8500MB) [applies to Scripting/Export/Archive.cpp
and Scripting/Export/Graphics.cpp].
Add a cmake option so I can skip building some parts and focus on
the rest.
=> build: add cmake option to skip Lua components

src/SLADEMap/MapObject/MapLine.cpp
issue mentioned here https://github.com/sirjuddington/SLADE/issues/1220
is caused by a std::bad_variant_access exception
in the call stack in question 
https://github.com/sirjuddington/SLADE/blob/d55762dad1cd40f9791e4150aa93963de142ce75/src/SLADEMap/MapObject/MapLine.cpp#L939
https://github.com/sirjuddington/SLADE/blob/4f8aac7007aaa931a2c41adaed798a59a2bdbc1b/src/Utility/Property.h#L84
the issue was: 
`backup->props_internal["s1"] = 0;`
was setting the "s1" property to a signed integer, instead of an unsigned integer
=> fix for std::bad_variant_access exception that causes issue #1220

src/Graphics/CTexture/TextureXList.h
When I tried to build the project using CMake and clang a while back, it failed due to a issue when it tried to disambiguate the argument list of a function with multiple overloaded signatures. Using a `std::static_cast` seemed to fix it, so I pushed it to my fork. The issue might just as well have been solved separately in upstream, but it might be worth taking a look into it anyway :)
=> Fixed slight issues when building for Clang

src/CMakeLists.txt, src/MapEditor/Renderer/MapRenderer3D.cpp
Address sanitizer causes crashes over inconsistent memory allocations
=> Fix flats/quads allocation in MapRenderer3D

src/General/ResourceManager.cpp, src/General/ResourceManager.h, src/Graphics/CTexture/CTexture.cpp, src/MainEditor/UI/TextureXEditor/PatchBrowser.cpp, src/MapEditor/MapTextureManager.cpp
This improves separation of flats from wall textures, and make flat texture selection work like in GZDoom (AFAIK anyway). This fixes a bug where flat textures weren't scaled if they used a high-res texture.
=> Fixes to flat texture selection

src/Graphics/SImage/Formats/SIFDoom.h, src/Graphics/SImage/SImage.cpp
This pull request adds the ability for SLADE to convert images to the PSX Doom graphic format. SLADE can already read this format very well; all that is required is to extend the capabilities to writing. Most of the code is also copied from similar code for other formats.
This change was motivated by the advent of new tools which enable mapping for PlayStation Doom, and the reverse engineered PC backport, PsyDoom.
Note that this change is primarily intended to help out mappers targeting 'PsyDoom'. For the native PSX engine you would also need to update the `TEXTURE1` lump if adding in new wall textures; PsyDoom plans to bypass use of that lump however to make modding easier. `TEXTURE1` just contains an array of `PSXPicHeader` (one for each wall texture in the game between `T_START` and …
=> Add the ability to convert to PSX DOOM format textures

src/Graphics/SImage/Formats/SIFDoom.h
The color 0,0,0 is considered fully transparent by the PSX hardware. If opaque black is used in a source image then it must be converted to a color close to black for the PSX format. Failure to do this can result in 'holes' in the image where black is used.
=> Fix fully black pixels being made transparent when converting to the PSX image format

src/Scripting/Lua.cpp
All of the functions have apparently been changed to start with capital letters, but `new_print` hasn't been updated to use the new capitalization. Since Lua is case-sensitive, that means issue #1134 has returned. This pull request fixes the issue.
When was this capitalization change made, however? If it's only in the beta for 3.2.0, and not any prior versions, then rather than merging this pull request, I think it would be better to just revert the capitalization change. Unless it serves some important purpose I'm unaware of, it seems like a needless change that breaks compatibility with old scripts for no apparent benefit. It is of course up to you; that's just my advice.
=> Change "print" from "logMessage" to "LogMessage"

src/Application/SLADEWxApp.cpp, src/Archive/Formats/DatArchive.cpp, src/Archive/Formats/ZipArchive.cpp, src/Audio/AudioTags.cpp, src/Audio/MIDIPlayer.cpp, src/Dialogs/GfxConvDialog.cpp, src/Dialogs/MapReplaceDialog.cpp, src/MainEditor/ArchiveOperations.cpp, src/MainEditor/UI/EntryPanel/DataEntryPanel.cpp, src/MainEditor/UI/StartPage.cpp, src/MapEditor/Edit/Edit2D.cpp, src/MapEditor/MapEditContext.cpp, src/Utility/Tokenizer.cpp
Fix assorted format string bugs which caused lots of failed assertions in wxArgNormalizer(): format specifier doesn't match argument type.
=> Fix wrong format strings when calling S_FMT() macro

src/External/zreaders/portable_endian.h
Just as on OpenBSD, `#include <sys/endian.h>` is enough without any extra macro (re)definition; in fact, doing that breaks the build.
=> Fix endianness support on FreeBSD

src/CMakeLists.txt, src/MainEditor/UI/EntryPanel/AudioEntryPanel.cpp, src/MainEditor/UI/EntryPanel/AudioEntryPanel.h
wxWidgets could be compiled without multimedia support, so make MP3 playback conditional on whether `wxUSE_MEDIACTRL` macro is defined.
This has been extensively tested as part of the FreeBSD port for quite a while, and does not cripple normal editing operations in any way.
=> Allow to build against wxWidgets built without multimedia support

.github/workflows/continuous_integration.yml, src/CMakeLists.txt, src/Scripting/Export/General.cpp, src/common.h
This supersedes #1271 but without useless changes.
[Here](https://github.com/alexey-lysiuk/SLADE/actions/runs/1109826553) is this build in my fork. Windows targets are more complicated as they need dependency packages for Win32 and x64, or `vcpkg` with a cache for built libraries.
=> Fixes for macOS + continuous integration workflow

src/UI/Dialogs/Preferences/BaseResourceArchivesPanel.cpp
If nothing is selected, index == -1 and we hit an assertion a little further
down the call stack.  Avoid it entirely; nothing to do here.
=> UI: avoid an assertion with no base archive selected

src/MainEditor/UI/ArchiveManagerPanel.cpp
The functionality was inadvertently removed in c97108db8, while the links
themselves remained.  They could arguably be removed altogether, but they're
pretty handy to have available.
=> UI: fix start page create archive links

dist/res/actions/arch.cfg, src/CMakeLists.txt, src/Graphics/CTexture/TextureXList.cpp, src/Graphics/CTexture/TextureXList.h, src/MainEditor/ArchiveOperations.cpp, src/MainEditor/ArchiveOperations.h, src/MainEditor/EntryOperations.cpp, src/MainEditor/EntryOperations.h, src/MainEditor/UI/ArchivePanel.cpp, src/MainEditor/UI/ArchivePanel.h
This adds 2 right click options for texture entries and an archive maintenance option for finding all unused zdoom textures.
Doom style and Zdoom style textures both have an option to clean out duplicate unmodified texture entries that also exist in the iwad.
Zdoom style textures also have another option to clean out redundant single patch textures and convert those patches into textures themselves.
The Remove Unused Zdoom textures option scans through all wall and floor/ceil textures in every map similar to the existing remove unused textures/remove unused flats tools.  Except remove unused textures currently doesn't check floor/ceil, and remove unused flats currently doesn't check walls.  Also I have a rudimentary Animdefs parser to add animated and switch textures to the exclude list. …
=> ZDoom Texture Cleanup Operations

src/Graphics/SImage/SImageFormats.cpp
They are now actually displayed properly instead of being solid-filled with a single color.
Before:
After:
=> Fix loading of Jaguar textures

src/MainEditor/UI/ArchivePanel.cpp
The sizer contains the splitter, which contains the two panes.  When an
archive entry is deleted, the splitter's the one that we need to be
replacing it in.
This fixes an assertion when an archive entry is deleted, then another one
is selected. This regression seems to be from eb6eeb5db6fa, when the
splitter was introduced.
=> ArchivePanel: deleted windows should be replaced in the splitter

.github/workflows/continuous_integration.yml
SLADE now officially requires at least wxWidgets 3.1.0, so update the CI script to use some custom wx3.1 packages from CodeLite
=> Update CI script to download/use wx3.1 for linux

src/Graphics/Icons.cpp, src/Graphics/Icons.h, src/MainEditor/UI/ArchiveManagerPanel.cpp, src/Scripting/UI/ScriptManagerWindow.cpp, src/TextEditor/UI/SCallTip.cpp, src/TextEditor/UI/TextEditorCtrl.cpp, src/UI/Controls/SIconButton.cpp, src/UI/Controls/STabCtrl.h, src/UI/Dialogs/MapEditorConfigDialog.cpp, src/UI/Lists/ArchiveEntryList.cpp, src/UI/Lists/ArchiveEntryTree.cpp, src/UI/SAuiTabArt.cpp, src/UI/SAuiTabArt.h, src/UI/SToolBar/SToolBarButton.cpp, src/UI/SToolBar/SToolBarButton.h, src/UI/WxUtils.cpp, src/UI/WxUtils.h
Whew, what a mess.
wx3.1.6 introduces wxBitmapBundle and a bunch of its own DPI handling, which completely broke a bunch of SLADE's custom handling.
Luckily it mostly seems limited to icon/image stuff, so changing getIcon to return a wxBitmapBundle and updating code to work with that seems to work for most things from what I can tell.
Resolves #1341
=> Update for wx3.1.6+ compatibility

src/MapEditor/Renderer/MapRenderer3D.cpp
The array was being used uninitialized causing random crashes.
=> [3d_floors_eevee_adapted] Fix 3d-mode segmentation faults by zero-initializing visible flats array

src/MapEditor/MapEditor.cpp, src/MapEditor/Renderer/MapRenderer3D.cpp
It was actually being forwarded to the target sector from the control sector, causing ambiguous issues like when you changing the 3d floor height/textures you were changing the ones in the sector it was over instead.
=> [3d_floors_eevee_adapted] Fix editing of 3d floors properties not being correctly forwarded to the control sector

msvc/SLADE.vcxproj, msvc/SLADE.vcxproj.filters, src/Archive/Archive.cpp, src/Archive/Formats/WadArchive.cpp, src/Game/Configuration.cpp, src/Game/Game.cpp, src/General/Defs.h, src/MainEditor/ArchiveOperations.cpp, src/MainEditor/UI/EntryPanel/DataEntryPanel.cpp, src/MainEditor/UI/EntryPanel/DataEntryPanel.h, src/SLADEMap/MapFormat/Doom32XMapFormat.cpp, src/SLADEMap/MapFormat/Doom32XMapFormat.h, src/SLADEMap/MapFormat/MapFormatHandler.cpp, src/UI/Canvas/MapPreviewCanvas.cpp, src/UI/Dialogs/MapEditorConfigDialog.cpp
We go from this:
to this:
The format is detected by the presence of the "PLAYPALS" lump. which is unique to 32X WADs.
=> Add support for Doom 32X map format

dist/res/config/entry_types/types_misc.txt
Fixes fading masks lumps being incorrectly detected as "Graphic (Jaguar Tx)"
=> Fix SRB2 fading mask detection in a zip archive

dist/res/actions/arch.cfg, src/MainEditor/ArchiveOperations.cpp, src/MainEditor/ArchiveOperations.h, src/MainEditor/UI/ArchivePanel.cpp
Added some tools to find duplicate texture and patch entries in zdoom.  This will help manage large texture packs.  It'll check across Texture entries, texture files themselves, and flats.  The patch tool will detect duplicate patch names across the ptable and all the patch files that can exist in an archive.
Other types of duplicate entries should be easy to detect using the existing find duplicate named entries tool.
=> Some more zdoom texture managment tools

src/SLADEMap/MapSpecials.cpp, src/SLADEMap/MapSpecials.h
This doesn't covers up all the srb2's FOFs but over 98% of them, which I find good enough for production use.
=> [3d_floors_eevee_adapted] Add support for Srb2's Floor Over floors

dist/res/actions/arch.cfg, msvc/SLADE.vcxproj, msvc/ThirdPartyLib.vcxproj, src/MainEditor/ArchiveOperations.cpp, src/MainEditor/ArchiveOperations.h, src/MainEditor/UI/ArchivePanel.cpp
This adds tools that print out which entries your archive overrides from the iwad.
One version is for checking generic wads/archives.
The other version is specific to zdoom texture assets and checks across flats, patches, textures, etc...  This makes it easy to tell if you accidentally overwrote a patch from Doom with some texture name from one of your texture packs you're managing.
Here the generic EXIT1 patch is being overridden by some texture named EXIT1 and this will help catch all such cases.
Here's a printout of the conflicting entry name.  Turns out a texture from Chasm was also called EXIT1 and it's overriding the EXIT1 patch from Doom2.wad.  Time to rename it, and fix every other conflict in this printout.
=> Adding iwad override printout checks

src/Audio/AudioTags.cpp, src/MainEditor/UI/ArchivePanel.cpp
Two small crash/error fixes for Linux (for the most part):
1. A crash when opening a music file with an ID3v2 Copyright tag, due to a format string being invalid UTF-8.
2. A GTK+ critical warning due to improper usage of `wxMenuItem::SetBitmap()`.
=> Two small crash/error fixes for Linux

src/Application/SLADEWxApp.cpp, src/Game/Configuration.cpp, src/MapEditor/UI/MapCanvas.cpp, src/UI/Controls/ConsolePanel.cpp, src/UI/SToolBar/SToolBarButton.cpp
You won't believe how!  It's by turning off word wrap in the console (on wxGTK only; no reason to do it for anyone else).  See #1016 and wxWidgets/wxWidgets#23364.
This is a kludge until...  someone else fixes it for real.  But the drawback is pretty minor, considering I haven't been able to use SLADE for mapping at all for five and a half years.
The rest of this fixes some assertion failures and stderr spam.  Not sure why the map editor window's toolbar buttons are getting mouse events when it's not even open...
=> Fix SLADE on Linux

src/MapEditor/UI/MapCanvas.cpp
On Linux with high DPI I had the same issue as #891. I tried out the fix for Mac and it worked for Linux as well.
Also tested and it works with fractional scaling and with no scaling.
=> Fixed 3D Camera spinning issue on Linux with High-DPI

thirdparty/lunasvg/include/lunasvg.h, thirdparty/lunasvg/source/property.h
No release has been made with these, so this is a simple backport Upstream https://github.com/sammycage/lunasvg/commit/db27b7c0ef987f222a87e24f4feec507cfe9635d
These includes are required, since the specific integer types are otherwise never declared.
=> Backport missing lunasvg imports

src/General/UI.cpp, src/UI/Controls/ConsolePanel.cpp
`GetDPIScaleFactor` was only introduced in 3.1.4
`StartStyling` had its argument count reduced from 2 to 1 in 3.1.1 (no overload exists, despite being possible in C++)
=> Add wxWidget verison checks to lower min required version

src/Application/SLADEWxApp.cpp
`test[123]` would result in `*(test+123)`, which may point to valid memory that we modify. Instead dereference the null pointer directly to ensure we actually crash
=> dereference null pointer directly in crash command

src/CMakeLists.txt
Allows specifying a custom wx-config tool at configuration time (for example if multiple are available)
Passes the config tool to the wxWidgets package, allowing it to find the libraries.
=> Allow setting a custom wx_config tool at configuration time, pass wx_config tool to package

dist/res/config/ports/include/specials_zdoom.cfg
Apologies for making a request for such a tiny, almost pointless change. I just happened to notice this special was missing because I needed it for the map I'm working on, and that was bothering me. I could have just changed my local `slade.pk3` and left it at that, but I thought maybe someone else will stumble upon this at some point, so might as well fix the issue for everyone.
=> Add missing special 107

dist/res/config/languages/acs.txt
Correction for spelling SetHudClipRect, SetHudSize and SetHudWrapWidth, so Function Link works.
ACS demo code:
```
#include "zcommon.acs"
script 1 (void)
{
// url does not work
SetHUDSize(320, 200, true);
SetHUDClipRect(10, 10, 180, 180, 90, true);
SetHUDWrapWidth(100);
// corrected
SetHudSize(320, 200, true);
SetHudClipRect(10, 10, 180, 180, 90, true);
SetHudWrapWidth(100);
}
```
=> ACS upper case HUD

dist/res/actions/mapw_general.cfg, dist/res/icons.cfg, dist/res/icons/general/run_quick.svg, src/MapEditor/UI/MapEditorWindow.cpp
Added a purple "Quick Run" button to the map editor toolbar that runs the current map without opening the run dialog. Quick Running a map uses the configuration options provided the last time the map was run.
=> Added Quick Run button

dist/res/config/ports/eternity.cfg, dist/res/config/ports/include/props_eternity.cfg
This adds and enables the per-texture sidedef offsets and Eternity's new skew properties. I couldn't find a way to do a string list for the prop so the skew props are just standard string types.
=> Update Eternity UDMF

CMakeLists.txt, src/CMakeLists.txt, src/Utility/Colour.h
Alternate take on #1208 since original author has not responded.  This addressing the narrowing conversion error a different way (is ColRGBA supposed to have an unused blend parameter?), and keeps the sse compile option functioning on x86.
Plus a couple of tiny CMakeLists changes to allow CMAKE_MODULE_PATH to be modified by the builder (allows some flexibility in build environments) and indicate that project is tested compatible with CMake 3.26.
=> Fixed build under aarch64

net.mancubus.SLADE.metainfo.xml
It now passes `appstream.cli validate --strict net.mancubus.SLADE.metainfo.xml`
=> Update metainfo file

src/SLADEMap/MapObject/MapLine.cpp, src/SLADEMap/MapObject/MapObject.cpp, src/SLADEMap/MapObject/MapSector.cpp, src/SLADEMap/MapObject/MapSide.cpp, src/SLADEMap/MapObject/MapThing.cpp
These copy methods are used by the "paste properties" action and this resolves some bugs with using Undo after those actions, including https://github.com/sirjuddington/SLADE/issues/1587 which I filed earlier.
=> ensure map objects call setModified in copy method to play nicely with Undo

src/Graphics/SImage/SImageFormats.cpp
This matches behavior of Calico Doom's renderer and also adds support for lumps that contain unaligned column data, where a single post byte of 0xFF is used a post:
https://github.com/team-eternity/calico-doom/blob/master/src/r_phase8.c#L39
=> Only check the MSB of the Jaguar sprite post for 0xFF

src/General/KeyBind.cpp
The default keyboard shortcut for Split Nearest Line in the map editor is Ctrl-Shift-S which is also the key shortcut for Map Save As. If you press Ctrl-Shift-S in the map editor, it will split the nearest line and simultaneously open the Map Save As dialog. If you are just trying to split a line, this is inconvenient. If you are trying to save the map under a different name, you will probably not notice that you also split a line. Nothing is bound to Shift-S, so this changes the default binding for the Split Nearest Line action to Shift-S.
=> Change split line shortcut to Shift-S to avoid clash with Map Save As

src/MapEditor/Edit/MoveObjects.cpp
Resolves https://github.com/sirjuddington/SLADE/issues/389 .
It works by checking if all the vertices for each sector are being moved and moving the contained things if they are.
=> Feature: move things in moved sectors

dist/res/config/entry_types/gfx_doom.cfg, src/Archive/EntryType/DataFormats/ImageFormats.h, src/Archive/EntryType/EntryDataFormat.cpp, src/Graphics/GameFormats.h, src/Graphics/SImage/Formats/SIFDoom.h, src/Graphics/SImage/SIFormat.cpp
I would like to use the Jaguar image format for wall textures for the next version of Doom 32X Resurrection, hence the change. The "standard" texture format in JagDoom is rather silly since there's no header at all and the only way to auto-detect it is by checking if the 320-byte footer in the lump matches the initial 320 bytes. With 100 textures, that would require roughly 32KB of ROM space, which is just too wasteful, since the data in the footer is redundant to begin with.
So my plan is to re-use the JaguarImage format used for 2D gfx for wall textures, but also extend it by adding two new flags in the unused padding space of the header:
- bitflag of 1 indicates the column-major format
Before:
After:
=> Extend the Jaguar image format and add conversion option

src/MapEditor/MapEditContext.cpp
Triggering the Mirror Horizontally or Mirror Vertically actions during Edit Objects seems to put things into a weird state where if you commit the Edit Object changes, the sectors are completely broken and cannot be fixed with Undo. Since Edit Objects already handles mirroring the objects in its own way, it makes sense to disable these actions that will break your map if used.
=> Disable Mirror Horizontally/Vertically during Edit Objects

src/MapEditor/UI/ObjectEditPanel.cpp
If you use the Edit Object(s) functionality and apply a change with Mirror X or Mirror Y selected, those checkboxes don't get initialized properly and remain checked when you enter Edit Object(s) mode again, and you have to click them twice to actually mirror the object. This code change fixes that.
=> initialize object edit panel mirror checkboxes properly

src/MapEditor/Edit/ObjectEdit.cpp
When scaling a selection of things in Edit Objects mode, and clicking the Preview button, the locations of the things are scaled from a corner of the bounding box instead of the center, this actually puts things outside the scaled bounding box. This code change brings the scaling of thing positions to match that of vertices.
=> Edit Objects: scale things the same way vertices are scaled, from center of bounding box

src/General/KeyBind.cpp, src/MapEditor/Edit/Input.cpp
This adds a feature in 2D Map (things) mode to rotate selected things with the < and > (comma and period) keys. It resolves this request: https://github.com/sirjuddington/SLADE/issues/1568 except not using the suggested [ and ] keys because those are already used to change grid size. Edit: I added Undo support.
=> Add < and > keybinds to rotate things in 2D Map Edit (things) mode

src/MapEditor/ItemSelection.cpp
In the map editor when switching from sector mode to things mode, it will select any things that are inside the formerly selected sectors. It resolves https://github.com/sirjuddington/SLADE/issues/392
=> transfer selection from sectors to things in the map editor

src/Graphics/SImage/Formats/SIFDoom.h
The new values for the 'flags' are supposed to extend functionality of the 4-bit images.
Enabled bit 1 indicates that the base palette index is odd.
If bit 2 is enabled, palette indices must be doubled. This allows creating images with more contrast.
The status bar on the screenshot has only 16 unique colors and uses both new flags to achieve good visual results:
=> Add support for flags 2 and 4 for 4-bit Jaguar Images

src/Application/App.cpp
The 3d mode camera spins like crazy if this permission is not given to Slade. So this shows a Pop Up that tells the user how to fix it
Before this, users needed to google or ask someone how to fix this problem
=> Request Accessibility Permissions on Mac

cmake/unix.cmake
Should make [this](https://github.com/sirjuddington/SLADE/issues/1633#issuecomment-1865962537) unneeded.
=> Fix compiling for clang and gcc version 9 and greater

cmake/cmake_uninstall.cmake.in, cmake/unix.cmake
- Replace calls to deprecated exec_program with execute_process when using uninstall target
- Add comment for uninstall target
- Only install slade.pk3 if BUILD_PK3 is enabled (fixes #1641)
=> CMake cleanup and fixes

src/TextEditor/UI/SCallTip.cpp, src/TextEditor/UI/SCallTip.h
Stop using some deprecated `wxBitmap` methods (`wxBitmap::SetWidth`, `wxBitmap::SetHeight`) which have been deprecated since
wxWidgets 3.1.2 and are removed in the current v3.3 development trunk.
With this SLADE builds fine on the current wxWidgets 3.3 development trunk.
I also verified the changes against wxWidgets (wxGTK) 3.0.5 and 3.2.4.
=> Replace deprecated wxBitmap methods (fix build on wxWidgets 3.3)

dist/res/config/entry_types/text.cfg
Files with the .zs, .zsc or .zc are now recognized as ZScript files.
https://forum.zdoom.org/viewtopic.php?p=1249322#p1249322
=> Recognize ZScript files by extension

.github/workflows/continuous_integration.yml
Update linux CI workflow to Ubuntu 24.04 LTS (since we need wxWidgets 3.2+ now)
=> Update linux CI workflow to 24.04

net.mancubus.SLADE.desktop
Keywords taken from Github topics
Adds keywords as specified here: https://webcache.googleusercontent.com/search?q=cache:https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html
These are also used by Flathub, KDE Discover and Gnome Software.
As an example, check the Ghidra .desktop file and Flathub page:
https://github.com/flathub/org.ghidra_sre.Ghidra/blob/master/org.ghidra_sre.Ghidra.desktop
```
Keywords=reverse-engineering;disassembler;disassembly;assembler;assembly;asm;decompile;decompilation;software-analysis;security;
```
https://flathub.org/apps/org.ghidra_sre.Ghidra
=> Add keywords to .desktop file

src/Audio/MIDIPlayer.cpp
This call causes the soundfont to reset to default if a MIDI entry is played and any of the Play, Pause or Stop buttons get pressed after playback has already started. This results in all instruments being reset back to a default piano once playback resumes for the selected MIDI entry.
This patch addresses the issue I experienced in https://github.com/sirjuddington/SLADE/issues/1737 where playing a MIDI entry works fine, but the soundfont disappears after the Play, Pause or Stop buttons are clicked.
The `stop()` function calls out to `fluid_synth_system_reset(fs_synth_)` which breaks the soundfont for the selected MIDI entry. Once playback is resumed, all instruments other than the drumkit have been reset to default MIDI pianos.
=> Don't reset fluid_synth in MIDIPlayer.cpp stop()

.github/workflows/continuous_integration.yml
The artifacts are uploaded after every commit to https://github.com/sirjuddington/SLADE/actions
After every release, it takes a while to compile, but they get uploaded automatically
https://github.com/Pedro-Beirao/SLADE/releases/tag/3.2.7.2
This PR only deals with x64 and arm64 macOS, the other platforms are harder for me to implement
(also fixed the Linux dependecies error that has been occurring for a while)
=> Add macOS CI artifacts uploading

.github/workflows/continuous_integration.yml
- Dont delete release description when uploading artifacts
https://github.com/kraflab/dsda-doom/commit/2a6741c70786ada4da588fdccd7d7c24d048ea69
- Add retry create dmg step on macOS CI
There is a bug with the macos-13 runner where `hdutil` fails randomly https://github.com/actions/runner-images/issues/7522
So this implements retries like many other projects have done
=> Small CI fixes

src/General/KeyBind.cpp, src/MapEditor/Edit/Edit3D.cpp, src/MapEditor/Edit/Edit3D.h, src/MapEditor/MapEditContext.cpp, src/SLADEMap/MapObject/MapLine.cpp, src/SLADEMap/MapObject/MapLine.h, src/SLADEMap/MapObject/MapSide.cpp, src/SLADEMap/MapObject/MapSide.h
This addresses bidirectional alignment as mentioned in #400 and y-alignment as mentioned in #486. These are the aspects implemented:
- Automatic horizontal (x-) texture alignment in both directions (#486)
- Automatic vertical (y-) texture alignment using vanilla DOOM single y-offset per side and taking pegging into account (#400)
Aspects not implemented:
- auto-justification as mentioned in #486.
- application of individual y-offsets for upper, middle and lower wall part as supported by UDMF, for example.
This supersedes my previous pull request #1780 as I restructured the alignment implementation to minimize code duplication and extensive parameter passing, and extended the scope to generalized auto-alignment.
As this is limited to the single y-offset from vanilla DOOM, vertical …
=> Automatic bidirectional alignment in x and y direction

src/MainEditor/EntryOperations.cpp
The Java maximum heap size for DECOHack is currently being set to 4GB, the same as in the DoomTools scripts. This is too high for 32-bit versions of Java, and as Slade still supports 32 bits, I have lowered this to 1GB.
=> Lower Java max allocation to 1GB

thirdparty/CMakeLists.txt
This stopped working since pkg-config stopped being used elsewhere.
=> Fix CMake USE_SYSTEM_DUMB option

dist/res/actions/arch.cfg, src/MainEditor/UI/ArchivePanel.cpp, src/MainEditor/UI/MainWindow.cpp
Adds a 'Quick Run Archive' button to the archive view similar to the 'Quick Run Map' button found in the map editor (#1531). Executes the current run configuration without showing the configuration dialog.
=> Added 'Quick Run Archive' button

.github/workflows/continuous_integration.yml
Linux artifacts should be uploaded, just like macOS ones.
FYI your release mechanism is also broken (I think) so maybe I could fix that too.
=> Upload Linux artifacts
